version: 0.0
os: linux
files:
- source: /
 destination: /home/ubuntu/node

permissions:
- object: /
   pattern: "**"
   owner: ubuntu
   group: ubuntu

hooks:
AfterInstall:
   - location: bin/install-pkgs
     timeout: 1200
     runas: root

ApplicationStart:
   - location: bin/app-start
     timeout: 60
     runas: root
