version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/node
hooks:  
BeforeInstall: 
  - location: scripts/beforeinstall.sh
    timeout: 300
    runas: root
AfterInstall:
  - location: scripts/installpkgs.sh
    timeout: 120
    runas: root
ApplicationStart:
  - location: scripts/appstart.sh
    timeout: 120
    runas: root
  
