version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/node
  permissions:
  - object: /home/ubuntu/node/scripts
    owner: root
    group: root
    mode : 777
    type : 
         - directory
    
hooks:  
BeforeStart: 
  - location: scripts/before-install.sh
    timeout: 300
    runas: root
AfterInstall:
  - location: scripts/install-pkgs.sh
    timeout: 120
    runas: root
ApplicationStart:
  - location: scripts/app-start.sh
    timeout: 120
    runas: root
  
