version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/node
  permission:  
   - object: /home/ubuntu/node
     owner: ubuntu
     group: ubuntu
     mode: 777
     type 
       - directory
hooks:  
BeforeInstall: 
  - location: scripts/beforeinstall.sh
    timeout: 300
    runas: root
AfterInstall:
  - location: scripts/installpkgs.sh
    timeout: 120
    runas: root
ApplicationStart:
  - location: scripts/appstart.sh
    timeout: 120
    runas: root
  
