openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'GoalServe'
  description: 'This is an API documentation of GoalServe'
servers:
  - description: Deploy server
    url: http://192.168.1.124:3003
  - description: localmachine server
    url: http://localhost:3003
tags:
  - name: User
    description: Operations about user
  - name: Sub User
    description: Operations about sub user
paths:
  /users/login:
    post:
      tags:
        - User
      summary: Logs user into the system
      operationId: loginUser
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  description: Login Email
                  type: string
                password:
                  description: Login Password
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Invalid username/password supplied
  /user/signup-via-email:
    post:
      tags:
        - User
      summary: User SignupViaMail
      operationId: userSignup
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  description: Signup Email
                  type: string
                redirectUrl:
                  description: Need to confrim your Email
                  type: string
              required:
                - email
                - redirectUrl
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  /user/confirm-registration:
    post:
      tags:
        - User
      summary: User confrim registration
      operationId: confirm user registation
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                token:
                  description: Need token to confrim registration
                  type: string
                password:
                  description: Enter your desired password
                  type: string
                passwordConfirmation:
                  description: Please Re-enter your password
                  type: string
              required:
                - token
                - password
                - passwordConfirmation
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  /user/password/request-reset:
    post:
      tags:
        - User
      summary: User reset password registration token
      operationId: reset password registration token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  description: Please enter your registered email
                  type: string
                redirectUrl:
                  description: Need to reset your password
                  type: string
              required:
                - email
                - redirectUrl
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  /user/password/set:
    post:
      tags:
        - User
      summary: set your new password
      operationId: register new password
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                token:
                  description: Need token to set password
                  type: string
                password:
                  description: Enter your desired password
                  type: string
                passwordConfirmation:
                  description: Please Re-enter your password
                  type: string
              required:
                - token
                - password
                - passwordConfirmation
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  "/user/add-subuser/{parentUserId}":
    post:
      tags:
        - Sub User
      summary: Add a new sub user
      operationId: new sub user
      parameters:
        - in: path
          name: parentUserId
          required: true
          description: Need parent user id to add sub user
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  description: sub user name
                  type: string
                email:
                  description: Enter your registered Email
                  type: string
                phone:
                  description: Please enter the phone number
                  type: string
              required:
                - name
                - email
                - phone
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  "/user/update-subuser/{parentUserId}/{subUserId}":
    post:
      tags:
        - Sub User
      summary: Update details of the sub user
      operationId: update sub user
      parameters:
        - in: path
          name: parentUserId
          required: true
          description: Need parent user id to update sub users
          schema:
            type: string
        - in: path
          name: subUserId
          required: true
          description: Need sub user id to update individual sub user
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  description: update sub user name
                  type: string
                phone:
                  description: update the phone number
                  type: string
              required:
                - name
                - phone
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  "/user/delete-subuser/{parentUserId}/{subUserId}":
    delete:
      tags:
        - Sub User
      summary: Delete the sub user
      operationId: delete sub user
      parameters:
        - in: path
          name: parentUserId
          required: true
          description: Need parent user id to delete sub users
          schema:
            type: string
        - in: path
          name: subUserId
          required: true
          description: Need sub user id to delete individual sub user
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  "/user/list-subusers/{parentUserId}":
    get:
      tags:
        - Sub User
      summary: List all the sub users of a parent user
      operationId: list sub users
      parameters:
        - in: path
          name: parentUserId
          required: true
          description: Need parent user id to list the sub users
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  "/user/subuser-set-password/{userId}":
    post:
      tags:
        - Sub User Settings
      summary: Add a new sub user
      operationId: setSubUserPassword
      parameters:
        - in: path
          name: userId
          required: true
          description: Need sub user id to set password
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                password:
                  description: Password
                  type: string
                passwordConfirmation:
                  description: Password Confirmation
                  type: string
              required:
              - password
              - passwordConfirmation
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  
    delete:
      tags:
        - Company Branch
      summary: Delete the branch
      operationId: delete branch
      parameters:
        - in: path
          name: branchId
          required: true
          description: Need branch id to delete branch
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
  
    post:
      tags:
        - Employee Profile
      parameters:
        - in: path
          name: employeeId
          description: Employee Id to add employee Identity Proofs
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeIdentityProofs"
        description: To add employee identity proofs
      responses:
        "200":
          description: Successfully returns the response
        "400":
          description: Invalid input Parameters
        "401":
          description: Invalid Access Token
        "404":
          description: No data found
        "500":
          description: Internal Server Error