var mongoose = require('mongoose');
var Schema = mongoose.Schema,
    ObjectId = Schema.ObjectId;

var pointSystemSchema = new Schema({
    "matchType" : { type: String, default: '' },
    "battingRun" : { type: String, default: '' },
    "battingBoundary" : { type: String, default: '' },
    "battingSix" : { type: String, default: '' },
    "battingHalfCentury" : { type: String, default: '' },
    "battingCentury" : { type: String, default: '' },
    "battingDuck" : { type: String, default: '' },
    "bowlingWicket" : { type: String, default: '' },
    "bowling4Wicket" : { type: String, default: '' },
    "bowling5Wicket" : { type: String, default: '' },
    "bowlingMaiden" : { type: String, default: '' },
    "fieldingCatch" : { type: String, default: '' },
    "fieldingStumpRunOut" : { type: String, default: '' },
    "fieldingRunOutThrower" : { type: String, default: '' },
    "fieldingRunOutCatcher" : { type: String, default: '' },
    "othersCaptain" : { type: String, default: '' },
    "othersViceCaptain" : { type: String, default: '' },
    "othersStarting11" : { type: String, default: '' },
    "t20EconomyLt4Runs" : { type: String, default: '' },
    "t20EconomyGt4Runs" : { type: String, default: '' },
    "t20EconomyGt5Runs" : { type: String, default: '' },
    "t20EconomyGt9Runs" : { type: String, default: '' },
    "t20EconomyGt10Runs" : { type: String, default: '' },
    "t20EconomyGt11Runs" : { type: String, default: '' },
    "odiEconomyLt2_5Runs" : { type: String, default: '' },
    "odiEconomyGt2_5Runs" : { type: String, default: '' },
    "odiEconomyGt3_5Runs" : { type: String, default: '' },
    "odiEconomyGt7Runs" : { type: String, default: '' },
    "odiEconomyGt8Runs" : { type: String, default: '' },
    "odiEconomyGt9Runs" : { type: String, default: '' },
    "t20StrikeLt50Runs" : { type: String, default: '' },
    "t20StrikeGt50Runs" : { type: String, default: '' },
    "t20StrikeGt60Runs" : { type: String, default: '' },
    "odiStrikeLt40Runs" : { type: String, default: '' },
    "odiStrikeGt40Runs" : { type: String, default: '' },
    "odiStrikeGt50Runs" : { type: String, default: '' },
});

module.exports = mongoose.model('point_systems', pointSystemSchema, 'point_system');